BUILDERS_COUNT = 5;
UPGRADERS_COUNT = 6;
HARVESTERS_COUNT = 7;
RANGED_ATTACK_CREEPS_COUNT = 5;
ATTACK_CREEPS_COUNT = 5;

MOVE_COST = 50;
WORK_COST = 100;
CARRY_COST = 50;
ATTACK_COST = 80;
RANGED_ATTACK_COST = 150;
HEAL_COST = 250;

module.exports = {
        BUILDERS_COUNT: BUILDERS_COUNT,
        UPGRADERS_COUNT: UPGRADERS_COUNT,
        HARVESTERS_COUNT: HARVESTERS_COUNT,
        RANGED_ATTACK_CREEPS_COUNT: RANGED_ATTACK_CREEPS_COUNT,
        ATTACK_CREEPS_COUNT: ATTACK_CREEPS_COUNT,
        MOVE_COST: MOVE_COST,
        WORK_COST: WORK_COST,
        CARRY_COST: CARRY_COST,
        ATTACK_COST: ATTACK_COST,
        RANGED_ATTACK_COST: RANGED_ATTACK_COST,
        HEAL_COST: HEAL_COST,
};
