BUILDERS_COUNT = 5;
UPGRADERS_COUNT = 6;
HARVESTERS_COUNT = 5;
RANGED_ATTACK_CREEPS_COUNT = 5;
ATTACK_CREEPS_COUNT = 5;

ATTACK_COST = 80;
RANGED_ATTACK_COST = 150;
HEAL_COST = 250;

module.exports = {
        BUILDERS_COUNT: BUILDERS_COUNT,
        UPGRADERS_COUNT: UPGRADERS_COUNT,
        HARVESTERS_COUNT: HARVESTERS_COUNT,
        RANGED_ATTACK_CREEPS_COUNT: RANGED_ATTACK_CREEPS_COUNT,
        ATTACK_CREEPS_COUNT: ATTACK_CREEPS_COUNT,
        ATTACK_COST: ATTACK_COST,
        RANGED_ATTACK_COST: RANGED_ATTACK_COST,
        HEAL_COST: HEAL_COST,
};
